version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: parking_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend